[project]
name = "uv-horses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arrow>=1.3.0",
    "python-dotenv>=1.0.1",
    "scrapy>=2.12.0",
    "scrapy-playwright>=0.0.42",
]
